HTTP/1.1 200 OK
Server: nginx
Date: Wed, 20 Nov 2019 14:17:23 GMT
Content-Type: application/hal+json
Content-Length: 510
Connection: close
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

{"resource":"customer","id":"cst_8wmqcHMN4U","mode":"test","name":"Remco Tolsma","email":"info@pronamic.nl","locale":null,"metadata":null,"createdAt":"2019-11-08T11:27:12+00:00","_links":{"self":{"href":"https://api.mollie.com/v2/customers/cst_8wmqcHMN4U","type":"application/hal+json"},"payments":{"href":"https://api.mollie.com/v2/customers/cst_8wmqcHMN4U/payments","type":"application/hal+json"},"documentation":{"href":"https://docs.mollie.com/reference/v2/customers-api/get-customer","type":"text/html"}}}
